FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/cmd/gateway
RUN go build -o gateway .

FROM gcr.io/distroless/base

COPY --from=builder /app/cmd/gateway/gateway /gateway

EXPOSE 8080

CMD ["/gateway"]