version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - CLOUD=azure
      - BUS_KIND=inmem
      - HMAC_SECRET=development-secret-key-32bytes-minimum-length-required
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8085/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3003:3003"
    environment:
      - WEB_PORT=3003
    depends_on:
      - gateway
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3003/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # 향후 확장을 위한 Redis (현재는 주석 처리)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data:

networks:
  default:
    driver: bridge
