FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/cmd/progression
RUN go build -o progression .

FROM gcr.io/distroless/base

COPY --from=builder /app/cmd/progression/progression /usr/local/bin/progression

ENV PORT=8080
EXPOSE 8080

CMD ["progression"]