FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/cmd/leaderboard
RUN go build -o leaderboard .

FROM gcr.io/distroless/base

COPY --from=builder /app/cmd/leaderboard/leaderboard /leaderboard

ENV PORT=8080

EXPOSE 8080

CMD ["/leaderboard"]