FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/cmd/gateway
RUN go build -o gateway .

FROM gcr.io/distroless/base

COPY --from=builder /app/cmd/gateway/gateway /gateway

EXPOSE 8085

# 환경변수 기본값
ENV PORT=8085
ENV CLOUD=azure
ENV BUS_KIND=inmem

CMD ["/gateway"]